[package]
name = "sample"
version = "0.1.0"
authors = ["xianzhan <424447832@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = {path = "bindings"}
windows = "0.9"
